### PR TITLE
chore: add action to auto-approve dependabot PRs

### PR DESCRIPTION
**Pull request by bgianfo**

### CODE REVIEW

**Review by adam-azarchs — APPROVED** [review]

**Comment by bgianfo** [comment]
I guess I don't have permissions to merge this?

**Comment by adam-azarchs** [comment]
Which means dependabot also doesn't have permissions to merge anything, which kind of makes the whole thing a bit pointless.

**Comment by adam-azarchs** [comment]
Or no, actually, I think the issue is that "require PRs to be up to date" is enabled in the branch protection rules.

**Comment by bgianfo** [comment]
> Or no, actually, I think the issue is that "require PRs to be up to date" is enabled in the branch protection rules.

That was it, thanks @github for making that so hard to see from your amazing UI! :smile:

**Pull request merged**
